version: '3.8'

services:
  app:
    build: 
      context: ./customer-network-backend
      dockerfile: ./Dockerfile.prod
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - app_network
    # command: sleep infinity

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: ./customer-network-backend/.env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

volumes:
  mysql-data:

networks:
  app_network:

  
